export const skills = [
  {
    category: "Frontend Engineering",
    skills: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "Redux",
      "GraphQL",
      "Remix",
      "Vite",
      "Storybook",
    ],
  },
  {
    category: "Backend Engineering",
    skills: [
      "Node.js",
      "Nest.js",
      "Go (Basic)",
      "Express",
      "PostgreSQL",
      "MongoDB",
      "MySQL",
    ],
  },
  {
    category: "Cloud, DevOps & Architecture",
    skills: [
      "AWS",
      "GCP",
      "Docker",
      "Kubernetes (Basic)",
      "CI/CD",
      "CircleCI",
      "GitHub Actions",
      "Microservices",
      "System Design",
      "API Design",
      "Performance Optimization",
      "Security",
    ],
  },
  {
    category: "Tools & Collaboration",
    skills: [
      "Jest",
      "RTL",
      "Git",
      "Cursor",
      "VsCode",
      "Figma",
      "Jira",
      "Confluence",
      "Slack",
      "Notion",
      "Asana",
    ],
  },
];
